######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 16 17:16:50 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plotter.h
SOURCES += main.cpp plotter.cpp
RESOURCES += plotter.qrc
