######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 3 11:01:44 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hexspinbox.h
SOURCES += hexspinbox.cpp main.cpp
