######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 5 20:24:38 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += iconeditor.h
SOURCES += iconeditor.cpp main.cpp
RESOURCES += iconeditor.qrc
